apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  selector:
    matchLabels:
      app: first-java-app
  template:
    metadata:
      labels:
        app: first-java-app
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
#          ports:
#            - name: http
#              containerPort: 8080
#              protocol: TCP